apiVersion: apps/v1
kind: Deployment
metadata:
  name: fasten-server-db-monster
  namespace: fasten
spec:
  selector:
    matchLabels:
      app: fasten-server-db-monster
  replicas: 2
  template:
    metadata:
      labels:
        app: fasten-server-db-monster
    spec:
      containers:
        - name: fasten-server-db
          image: monster93/fasten.server.db:v0.1b
          args: ["-k", "$(KAFKA_ADDR)", "-pl", "MetadataDBExtension", "-kt", "MetadataDBExtension=fasten.opal.cg.3", "-d", "$(PSQL_DB)", "-du", "$(PSQL_USER)"]
          ports:
            - containerPort: 3010
          env:
            - name: FASTEN_DBPASS
              valueFrom:
                secretKeyRef:
                  key: psql.pwd
                  name: psql-pwd
            - name: PSQL_DB
              valueFrom:
                configMapKeyRef:
                  key: psql.db.url
                  name: psql.db
            - name: PSQL_USER
              valueFrom:
                configMapKeyRef:
                  key: psql.db.username
                  name: psql.db.user
            - name: KAFKA_ADDR
              valueFrom:
                configMapKeyRef:
                  key: kafka.addr
                  name: kafka         
      nodeSelector:
        monster.node: "true"
